name: Go darwin
on: [push]
jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: master
        
    - name: Build
      run: |
        brew install pkg-config mpg123 portaudio faad2
        cp macOS/faad2.pc /usr/local/lib/pkgconfig/
        make -f Makefile.macOS
        install_name_tool -change @executable_path/output/bass/lib/macOS/libbass.dylib @executable_path/libbass.dylib hannah
        install_name_tool -change /usr/local/opt/mpg123/lib/libmpg123.0.dylib @executable_path/libmpg123.dylib hannah
        install_name_tool -change /usr/local/opt/faad2/lib/libfaad.2.dylib @executable_path/libfaad.dylib hannah
        mkdir darwin-amd64
        mv hannah darwin-amd64/
        cp output/bass/lib/darwin/amd64/libbass.dylib darwin-amd64/
        cp output/bass/lib/darwin/amd64/plugins/*.dylib darwin-amd64/
        cp /usr/local/lib/libmpg123.dylib darwin-amd64/
        cp /usr/local/lib/libfaad.dylib darwin-amd64/
        env GOPATH=$PWD/gopath go get -u github.com/missdeer/cicdutil

    - name: Upload artifact hannah-darwin-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: hannah-darwin-amd64
        # Directory containing files to upload
        path: darwin-amd64

    - name: Remove old artifacts
      run: |
        gopath/bin/cicdutil -p github -u missdeer -t ${{ secrets.GH_TOKEN }} -r hannah -k 0 -a delete