name: Go Darwin
on: [push]
jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - run: go version && go env

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: master
        
    - name: Build
      run: |
        brew install pkg-config
        make
        install_name_tool -change @executable_path/output/bass/lib/macOS/libbass.dylib @executable_path/libbass.dylib hannah
        mkdir darwin-amd64
        mv hannah darwin-amd64/
        cp output/bass/lib/darwin/amd64/libbass.dylib darwin-amd64/
        cp output/bass/lib/darwin/amd64/plugins/*.dylib darwin-amd64/
        cp cmd/reverseProxy/rp darwin-amd64/

    - name: Upload artifact hannah-darwin-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        name: hannah-darwin-amd64
        path: darwin-amd64
