name: Go Windows
on: [push]
jobs:

  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - mingw_arch: MINGW64
            mingw_prefix: mingw-w64-x86_64
            GOARCH: amd64
          - mingw_arch: MINGW32
            mingw_prefix: mingw-w64-i686
            GOARCH: 386

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.mingw_arch }}
          path-type: inherit
          install: ${{ matrix.mingw_prefix }}-toolchain ${{ matrix.mingw_prefix }}-openssl ${{ matrix.mingw_prefix }}-zstd ${{ matrix.mingw_prefix }}-mpg123 ${{ matrix.mingw_prefix }}-portaudio

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Build
        shell: cmd
        run: |
          set MSYSTEM=${{ matrix.mingw_arch }}
          set PATH=${{ runner.temp }}\msys\msys64\${{ matrix.mingw_arch }}\bin;%PATH%
          set CGO_ENABLED=1
          set GOARCH=${{ matrix.GOARCH }}
          set GOOS=windows
          path
          go build -ldflags="-s -w"
