name: Go Windows
on: [push]
jobs:

  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - mingw_arch: MINGW64
            mingw_prefix: mingw-w64-x86_64
            GOARCH: amd64
            GOOS: windows
          - mingw_arch: MINGW32
            mingw_prefix: mingw-w64-i686
            GOARCH: 386
            GOOS: windows

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.mingw_arch }}
          path-type: inherit
          install: ${{ matrix.mingw_prefix }}-toolchain

      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - run: go version && go env

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Build
        shell: cmd
        run: |
          set MSYSTEM=${{ matrix.mingw_arch }}
          set PATH=${{ runner.temp }}\msys\msys64\${{ matrix.mingw_arch }}\bin;%PATH%
          set CGO_ENABLED=1
          set GOARCH=${{ matrix.GOARCH }}
          set GOOS=${{ matrix.GOOS }}
          path
          go build -ldflags="-s -w" -o ${{ matrix.mingw_prefix }}\hannah.exe
          copy output\bass\lib\windows\${{ matrix.GOARCH }}\bass.dll ${{ matrix.mingw_prefix }}\
          copy output\bass\lib\windows\${{ matrix.GOARCH }}\plugins\*.dll ${{ matrix.mingw_prefix }}\
          copy ${{ runner.temp }}\msys\msys64\${{ matrix.mingw_arch }}\bin\libmpg123-0.dll ${{ matrix.mingw_prefix }}\
          copy ${{ runner.temp }}\msys\msys64\${{ matrix.mingw_arch }}\bin\libfaad-2.dll ${{ matrix.mingw_prefix }}\
          cd cmd\reverseProxy
          go build -ldflags="-s -w" -o ..\..\${{ matrix.mingw_prefix }}\rp.exe

      - name: Upload artifact hannah-${{ matrix.mingw_prefix }}
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: hannah-${{ matrix.mingw_prefix }}
          # Directory containing files to upload
          path: ${{ matrix.mingw_prefix }}